# Modelos Probabilísticos

## Introducción

Usualmente, y en el contexto de Marketing, estamos interesados en estudiar el comportamiento de las personas, de modo de entenderlo y realizar acciones estratégicas en función de los aprendizajes adquiridos. Así, se pueden definir dos tipos de enfoques a usar según distintos supuestos en el comportamiento de los agentes (tomadores de decisiones):

- *Enfoque Estructural*: Este enfoque asume que los los agentes se comportan de manera racional, tomando decisiones de modo de maximizar sus utilidades. Usualmente aparece cuando
hay disponibilidad de largos volumenes de datos.

- *Modelos Probabilísticos*:  Este enfoque asume que los agentes se comportan en base a decisiones aleatorias. Usualmente aparece cuando se tiene información reducida y/o agregada
respecto al comportamiento de los agentes en estudio.

En primera instancia, se estudiará el enfoque probabilistico, esto es, el enfoque en cual se asume que los tomadores de decisiones se comportan de manera aleatoria. Dicho enfoque posee una
metodología de modelamiento sugerida, que comparten todos los modelos que se verán a lo largo
del curso.


**Metodología**

La metodología consiste en:

1. Determinar el problema de decisión a estudiar y la información requerida.

2. Identificar el comportamiento observable de interés a nivel individual.

3. Seleccionar la distribución de probabilidad que caracterice el comportamiento individual. Se consideran los parámetros de esta distribución, como características latentes a nivel individual. 

4. Escoger la distribución que caracterice cómo las características latentes están distribuidas en la población. Se le llama distribución mixta o heterogénea. Típicamente, se denota con $g(\theta)$

5. Derivar la distribución agregada, o distribución observable, del comportamiento de interés. 

\begin{array}{cc}

f(x) = \int f(x|\theta) g(\theta) d\theta & \text{, para el caso continuo.}\\
 p(x) = \sum_{i} f(x|\theta)Pr(\theta = \theta_{i}) & \text{ 
 , para el caso discreto.}

\end{array}

6. Estimar los parámetros del modelo (de la distribución mixta), mediante el ajuste de la distribución agregada a los datos observados.

7. Usar los resultados para tomar una decisión sobre el problema de marketing en cuestión.

El enfoque de modelos probabilísticos permite abordar una gran cantidad de problemas asociados al Marketing, de entre los cuales se considerarán:

- *Timing*:  Situaciones ligadas a la duración de una determinada conducta de un cliente, como por ejemplo: tiempo de permanencia en una compañía y tiempo de adopción de un cierto producto innovador.

- *Conteo*: Situaciones ligadas al estudio de llegadas de clientes y contabilización de una determinada conducta, como por ejemplo: número de visitas a un portal web y la cantidad de productos comprados en una tienda de retail.

- *Elección*: Situaciones asociadas a las decisiones de elección de un determinado cliente, como por ejemplo: clientes que eligen responder una campaña publicitaria y la elección de cambiar o no de canal de televisión.

## Modelos de Duración

En años recientes, las mejoras en las tecnologías de información han dado como resultado un aumento en la disponibilidad de data acerca de los individuos en determinadas situaciones de consumo. Esta tendencia se relaciona íntimamente con el creciente deseo de los gerentes de marketing respecto a utilizar esta data disponible para aprender de manera exhaustiva sobre el comportamiento de los clientes. Muchos analistas tratan de describir y predecir el comportamiento de los consumidores usando variables observables, como lo son variables transaccionales (monto gastado, tienda donde se adquirió un determinado producto, fecha de la compra, etc.) como
así también variables que caracterizan a los individuos (edad, nivel socio-económico, estado civil, etc.). A partir de esta información es posible aplicar modelos de regresión lineal o árboles de decisión, con el objetivo de poder proyectar comportamientos o bien comprobar o rebatir hipótesis que previamente se tenían respecto a un escenario determinado.

En este capítulo, se considera un enfoque distinto al anterior, en el cual las decisiones de los individuos se desprenden de un comportamiento **aleatorio**, en que las decisiones no dependen únicamente de variables descriptivas del modelo, sino que también provienen del resultado de un proceso estocástico no observable que opera intrínsecamente en los individuos, es decir, la asunción que el comportamiento se desprende de una distribución de probabilidades que puede variar dependiendo del modelo a estimar y de la complejidad del mismo (alternativamente se puede considerar el enfoque racionalista que considera que los individuos siempre actúan en forma racional, lo que de acuerdo a la experiencia empírica, no se cumple siempre).

**Ejemplo 1**: Supongamos que un cliente hizo 2 compras el año pasado de nuestro producto. ¿Esto implica inmediatamente que el consumidor mantendrá ese patrón y este año volverá a ese nivel de consumo? ¿O existe alguna posibilidad de que el cliente incremente o disminuya su consumo? ¿Cuál es el proceso que hay detrás?

En lo que sigue, consideraremos 3 tipos de modelos a estimar:

1. **Modelos de duración en tiempo discreto.**

2. **Modelos de duración en tiempo continuo sin dependencia en la duración.**

3. **Modelos de duración en tiempo continuo con dependencia en la duración.**

### Modelos de duración de tiempo discreto

Supongamos el siguiente escenario: A través de una propuesta de valor atractiva, adquirimos
un cliente. ¿Durante cuántos periodos estará afiliado a la compañía? Se considera que cada periodo se puede cuantificar en términos discretos (días, semanas, meses, años). Algunos ejemplos a
considerar:

- Un usuario descarga una aplicación para su teléfono inteligente. ¿Por cuántos meses la utilizará?

- Adquirimos un cliente en un banco. ¿Durante cuántos años permanecerá como cliente?

- Un cliente se suscribe a un plan telefónico o de internet. ¿Por cuántos periodos se mantendrá
suscrito?

#### Modelo Geométrico Desplazado{-}

Asumamos que se tiene una cartera de clientes que van abandonando la relación comercial para nunca más retomarla en cualquier periodo definido. De acuerdo a lo descrito en las secciones anteriores, intentaremos describir de manera probabilística la situación. Supongamos que al final de cada periodo, un cliente decide de manera aleatoria si continúa afiliado a una determinada compañía, esto es, de acuerdo a un proceso de Bernoulli, decide con cierta probabilidad si cancela la relación comercial con la empresa (y con el coplemento respectivo decide su permanencia). Para cada individuo, asumiremos que la probabilidad con la cuál decide no cambia en el tiempo, denotándola $\theta$. Finalmente, y como primer acercamiento, asumiremos que dicha probabilidad es de igual forma idéntica a lo largo de individuos distintos (modelo homogéneo). Sea T la variable aleatoria relativa a la duración de la relación comercial entre el cliente y la compañía, es decir la variable que describe el instante en el cual esta relación se acaba. De acuerdo a la descripción anterior, la variable aleatoria T sigue una distribución Geométrica Desplazada (sG) con parámetro $\theta$, es decir, el comportamiento de los individuos puede ser descrito formalmente de acuerdo a la siguiente relación:

1.  Probabilidad de que un individuo cualquiera abandone la relación comercial exactamente
en el periodo t:

$$P(T=t| \theta) = \theta (1 - \theta)^{t-1}$$

2. Probabilidad de que un individuo cualquiera abandone la relación comercial en un periodo
posterior al periodo t:

$$P(T>t| \theta) = \theta (1 - \theta)^{t-1}$$

No es muy difícil aplicar un modelamiento a partir de lo anterior para intentar dilucidar de
qué forma se debería comportar un determinado grupo de individuos a partir de la data transaccional que se tiene. Veámoslo a partir de un ejemplo práctico:

**Ejemplo 2:** Consideremos un cohorte inicial de 1000 clientes (indexado por el número 0). Supongamos que año a año, un determinado número de clientes se retira del negocio por razones que se desconocen a priori, pero que asumimos provienen de un proceso estocástico en el que cada cliente en forma independiente toma la decisión de permanecer o abandonar a partir del lanzamiento de una moneda (Bernoulli), esto es, con probabilidad $\theta$ abandona y con probabilidad $1 - \theta$ permanece en la compañía. La data histórica se presenta a continuación:

| Año | # de Clientes | % de Permanencia | % de Retención |
|:---:|:-------------:|:----------------:|:--------------:|
|  0  |      1000     |       100%       |        -       |
|  1  |      631      |        63%       |       63%      |
|  2  |      468      |        47%       |       74%      |
|  3  |      382      |        38%       |       82%      |
|  4  |      326      |        33%       |       85%      |
|  5  |      289      |        29%       |       89%      |
|  6  |      262      |        26%       |       91%      |
|  7  |      241      |        24%       |       92%      |

Entendiéndose el % de Retención como el porcentaje de clientes que se mantuvo en la relación comercial respecto al periodo anterior.

Sin embargo, aún no sabemos cuanto vale $\theta$ (es un parámetro poblacional). Dicho valor lo estimaremos mediante el método de máxima verosimilitud, para el cual es necesario determinar la probabilidad de observar lo que efectivamente se está observando (densidad conjunta) asumiendo independencia entre las muestras:

- Densidad de probabilidades conjunta:

$$f(x_1,x_2,...,x_n|\theta) = f(x_1|\theta) \cdot f(x_2|\theta) \cdot ... \cdot f(x_n|\theta)$$

- Función de verosimilitud:

$$L(\theta|x_1,x_2,...,x_n) = \prod_{i=1}^n f(x_i|\theta) $$
A partir de esto y de la data disponible, las contribuciones a la verosimilitud son las siguientes
(asumiendo como modelo de comportamiento la distribución geométrica desplazada)

| Año | # de Clientes | # de Abandonos | Pr                                                           |
|-----|---------------|----------------|--------------------------------------------------------------|
|  0  |      1000     |        -       |                               -                              |
|  1  |      631      |       369      |                $P(T=1\|\theta) = \theta^{369}$               |
|  2  |      468      |       163      | $P(T=2\|\theta) = ((1 - \theta)^{(2-1)} \cdot \theta)^{163}$ |
|  3  |      382      |       86       |  $P(T=3\|\theta) = ((1 - \theta)^{(3-1)} \cdot \theta)^{86}$ |
|  4  |      326      |       56       |  $P(T=4\|\theta) = ((1 - \theta)^{(4-1)} \cdot \theta)^{56}$ |
|  5  |      289      |       37       |  $P(T=5\|\theta) = ((1 - \theta)^{(5-1)} \cdot \theta)^{37}$ |
|  6  |      262      |       27       |  $P(T=6\|\theta) = ((1 - \theta)^{(6-1)} \cdot \theta)^{27}$ |
|  7  |      241      |       21       |  $P(T=7\|\theta) = ((1 - \theta)^{(7-1)} \cdot \theta)^{21}$ |
|  >7 |       -       |        -       |            $P(T>7\|\theta) = ((1-\theta)^7)^{241}$           |

Dado que maximizar un producto es complicado, aplicamos logaritmo a lo anterior, de modo de construir la función de log verosimilitud:

- Función de log verosimilitud:

$$\hat{l}(\theta|x_1,x_2,...,x_n) = ln(L(\theta|x_1,x_2,...,x_n)) = \sum_{i=1}^n ln f(x_i|\theta)$$
Con lo anterior, es sencillo maximizar la función de log verosimilitud para un θ desconocido, con lo que se tiene:^[Se puede hacer fácilmente en excel a través de la herramienta solver. PROPUESTO]

$$\hat{\theta} = 0, 226027$$
$$\hat{l} = −1794, 62$$
El modelo antes presentado, si bien permite tomar medidas de gestión a partir de un modelo sencillo, es poco realista (pues se asume que la población posee igual probabilidad de abandono).

Una manera de incluir mayor complejidad al modelo y hacerlo más robusto, es asumiendo que la población no es homogénea, sino que existen segmentos de individuos quienes al ser agrupados, presentan un comportamiento similar. La forma más sencilla de modelar esto es asumiendo que la población presenta 2 patrones de comportamiento (2 segmentos), es decir, para un segmento de
individuos, la decisión de abandonar o permanecer se identifica a partir de un parámetro $\theta_1$ (del mismo modo que en el caso anterior), y para el otro segmento la decisión se determina a partir de un parámetro $\theta_2$ distinto de $\theta_1$. Formalmente, las relaciones que describen de mejor manera esto son las siguientes:

1. Probabilidad de que un individuo cualquiera abandone la relación comercial exactamente en el periodo t en una población con 2 segmentos:

$$P(T=t|\theta_1, \theta_2, \pi)= \theta_1 (1-\theta_1)^{t-1} \pi + \theta_2(1-\theta_2)^{t-1}(1-\pi)$$
2. Probabilidad de que un individuo cualquiera abandone la relación comercial en un periodo posterior al periodo t en una población con 2 segmentos:

$$P(T>t|\theta_1, \theta_2, \pi)= (1-\theta_1)^{t} \pi + (1-\theta_2)^{t}(1-\pi)$$

En el modelo anterior $\pi$ representa el porcentaje de la población que pertenece al segmento 1, de tal forma que su complemento $1-\pi$ representa el porcentaje de la población que pertenece al segmento 2.^[Este modelamiento es fácilmente expandible a 2 o más segmentos. PROPUESTO.]

#### Modelo Beta Geométrico desplazado{-}

Los modelos anteriores funcionan bien cuando la población se comporta de manera distinta entre clases latentes, y similar al interior de cada clase latente. Sin embargo, puede ser mucho más realista e interesante el asumir que existe una heterogeneidad continua en la población, es decir que existe un número infinito de segmentos (o al menos tendiente a infinito) de manera de capturar todas las preferencias individuales de cada miembro de la población considerada.

Para estos propósitos, ya no asumiremos que la probabilidad de abandono $\theta$ sigue una distribución discreta de Bernoulli (éxito-fracaso), sino que asumiremos que el parámetro proviene de una distribución continua Beta de parámetros $\alpha$ y $\beta$.

Por tanto, es posible calcular las probabilidades antes presentadas en forma análoga, aplicando el enfoque antes mencionado (probabilidades totales):

1. Probabilidad de que un individuo cualquiera abandone la relación comercial exactamente en el periodo t:

$$P(T=t|\alpha,\beta) = \int_0^1 (T=t|\theta)B(\theta|\alpha,\beta)d\theta$$
Recordar que:

$$B(\theta|\alpha,\beta) = \frac{\theta^{\alpha-1}(1-\theta)^{\beta-1}}{B(\alpha,\beta)}$$

$$B(\alpha,\beta) = \frac{\Gamma(\alpha)\Gamma(\beta)}{\Gamma(\alpha + \beta)}$$
2. Probabilidad de que un individuo cualquiera abandone la relación comercial en un periodo posterior al periodo t:

$$P(T>t|\alpha,\beta) = \int_0^1 (T>t|\theta)B(\theta|\alpha,\beta)d\theta$$
Al desarrollar la primera integral antes mencionada, y reconociendo las relaciones de la distribución *Beta*, se tiene que:

$$P(T=t|\alpha,\beta)= \frac{B(\alpha + 1, \beta + t -1)}{B(\alpha,\beta)}$$
Notar que, se usa indistintamente el $B(\alpha,\beta)$ para hacer alusión tanto a la **función** como a la **distribución Beta**. Bajo ninguna circunstancia dichos objetos son iguales.

**Ejemplo 3:**  Considerando la misma situación que se presentó en el ejemplo anterior (clientes que año a año abandonan la relación comercial), pero ahora asumiendo que existe un comportamiento heterogéneo en la población, es posible reconocer que existe una recursividad en la fórmula del cálculo de la probabilidad de abandono en cada período de la siguiente forma:

\begin{array}{cc}
P(T=t|\alpha,\beta) =
\begin{cases}
\frac{\alpha}{\alpha+\beta} & t=1
\\
P(T=t -1|\alpha,\beta) \frac{\beta + t -2}{\alpha + \beta + t -1} & t>1
\end{cases}
\end{array}

Modelo que al ser evaluado, da el siguiente resultado:

\begin{array}{c}
\hat{\alpha} = 0,7041\\
\hat{\beta}= 1,1820\\
\hat{l} = -1680,27
\end{array}

Notar que existe una notoria diferencia en cuanto al valor de la log verosimilitud obtenida por el modelo heterogéneo respecto al modelo homogéneo. Si bien, esto indica una mejora del modelo, es necesario realizar la comparación en base a métricas de evaluación mas precisas (AIC; BIC, etc.)

### Modelos de duración en tiempo continuo sin dependencia en la duración

Para algunos modelos, el medir el tiempo como si fueran períodos discretos puede ser un buena aproximación de acuerdo a los objetivos del análisis que se desea llevar a cabo.

En otros casos, puede ser en cambio más útil considerar el tiempo como una variable continua, debido a que podría interesar el medir la ocurrencia de un suceso de manera más exacta. Algunos casos relativos a este enfoque son:

- Tiempos de respuesta a una campaña promocional de marketing directo.

- Tiempo entre visitas a nuestro website.

- Tiempos entre llamadas en un call center.

- Tiempos de operación en la industria de servicios.

Al igual que en el caso de los modelos en tiempo discreto, lo que interesa es poder implementar un modelo que tenga una forma funcional flexible para ser trabajada y modificada fácilmente, que logre ajustar a la data histórica que se tiene, y que logre además proyectar el comportamiento futuro de los clientes, es decir, que sea un buen modelo predictivo para tomar acciones en función de aquello.

#### Modelo Exponencial{-}

Supongamos que nos interesa medir el tiempo que pasa desde que se lanza un producto hasta que el consumidor decide adquirirlo. Existen muchos factores externos que determinan esta decisión: exposición a publicidad, número de visitas a la tienda, llamadas recibidas por call center, entre otras. Nuevamente asumiremos que el comportamiento es aleatorio, es decir, que los consumidores deciden el momento en el cuál van a consumira partir de una distribución de probabilidades.

Esto podemos modelarlo a partir de la distribución exponencial.^[Recordar el curso de Investigación de Operaciones]

Supongamos la variable aleatoria T definida como el tiempo en que un cliente va a consumir nuestro producto por primera vez. Asumiremos que esta variable está exponencialmente distribuida con una tasa $\lambda$. De esta forma, se tiene que la función de distribución acumulada de la variable aleatoria será:

$$F(t) = P(T \leq t) = 1 - e^{-\lambda t}$$

Notar que el término anterior representa la probabilidad que un cliente consuma el producto **antes** de t.

Ahora bien, esto inmediatamente deja en evidencia una limitante a este modelo: para un t muy grande, todos los consumidores van a probar^{Recordar que lím e^{-t}=0}, lo cual no es una situación del todo realista. Es necesario, en consecuencia, imponer que existe una fracción de clientes dentro de la muestra considerada que nunca probará el producto y así es posible solucionar la limitante encontrada (2 clases latentes).

1. Segmeto que prueba: Tamaño $\pi$

\begin{array}{c}
\lambda = \theta\\
\Rightarrow P(T \leq t) = 1 - e^{-\theta t}
\end{array}

2. Segmento que no prueba: Tamaño(1-$\pi$)

\begin{array}{c}
\lambda = 0\\
\Rightarrow P(T \leq t) = 0
\end{array}

Luego, la probabilidad total será:

\begin{array}{c}
P(T \leq t) = P(T \leq t | \text{Prueba}) P(\text{Prueba}) + P(T \leq t | \text{No Prueba}) P(\text{No Prueba}) \\
= 1 - e^{-\theta t}\pi
\end{array}

Es importante notar que si bien el modelo describe probabilidades en tiempo continuo, la data aún se presenta y obtiene en tiempo discreto. Incorporando esto, es posible construir la función de log verosimilitud calculando las probabilidades de adopción del producto entre los limites del
intervalo temporal definido por el periodo de medición, es decir:

$$P(t_0 \leq T \leq t_1) = F(t_1) - F(t_0)$$
Por lo que la función de log verosimilitud se define como (considerando n periodos discretos para el cálculo): 

$$LL(\pi,\theta|\text{data}) = N_1 ln[P(1\leq T \leq 2)] + ... + (N_{panel} - \sum_{i=1}^{n}N_i)ln[P(T>n)]$$
Adicionalmente, es de interés calcular los valores predichos por el modelo, de modo de realizar predicciones futuras. F(t) representa la probabilidad que un cliente escogido aleatoriamente pruebe el producto en t (tal que t = 0 corresponde al instante de lanzamiento del producto. La estimación del futuro se puede hacer a través de la esperanza:

$$\mathbb{E}[T(t)] = N_{\text{panel }} \cdot \hat{F}(t) $$

Antes de avanzar, es importante aclarar la distinción de un modelo *sin dependencia en la duración*. Esto se puede explicar con la propiedad fundamental de la distribución exponencial:

**Propiedad fundamental:** La distribución exponencial no tiene memoria, es decir, poseer información de que un elemento ha sobrevivido un tiempo ’s’ hasta este momento no modifica la probabilidad de que sobreviva un periodo t más. Es decir la probabilidad de que ocurra un suceso no depende del tiempo en que aún no ha ocurrido. Se puede demostrar matemáticamente:

$$P(T > s + t|T>s) = \frac{P(T> s+t)}{P(T> s)} = \frac{1-P(T \leq s+t)}{1-P(T \leq s)}= \frac{e^{-\lambda(s+t)}}{e^{-\lambda s}} = e^{-\lambda t}$$
#### Modelo Gamma Exponencial {-}

Análogamente a la situación anterior, ahora se asume que el comportamiento de la población es heterogéneo, es decir, que existen diferentes clases de clientes en la población. Esto busca complejizar la suposición que antes hicimos al considerar un grupo de clientes que nunca consume.

Por tanto, el modelo heterogéneo ahora considerará que la tasa de prueba $\lambda$ se distribuye *Gamma* en la población:

$$g(\lambda) = \frac{\alpha^r \lambda^{r-1} e^{-\alpha \lambda}}{\Gamma(r)}$$
Dónde r es un parámetro de forma y $\alpha$ es un parámetro de escala.

Al incorporar la heterogeneidad mencionada, la probabilidad que un cliente adquiera un producto antes de un tiempo t es la siguiente:




\begin{array}{cc}
P(T\leq t) &= \int_{0}^{\infty} P(T \leq t|\lambda) g(\lambda)d \lambda\\
&= 1 - (\frac{\alpha}{\alpha + t})^r
\end{array}

Este modelo lo llamaremos *Gamma Exponencial*.

### Modelos de duración en tiempo continuo con dependencia en la duración

Otra de las grandes limitantes del modelo *Exponencial* es que posee pérdida de memoria, es decir la probabilidad de adopción de un cliente no cambia a medida que pasa el tiempo. Se necesita incorporar esta distinción, es decir, la probabilidad de que un evento ocurra dado que hasta este momento no ha ocurrido. Esto último se conoce como *tasa de riesgo* o *hazard rate*:

$$h(t) = \frac{f(t)}{1 - F(t)}$$

Gráficamente, la tasa de riesgo se comporta de la siguiente manera 1.1:

**AQUÍ VA UN SET DE GRÁFICOS, PREGUNTAR**


En el primer caso, la intuición es que si una persona no ha respondido a un e-mail, cada vez es menos probable que lo responda, pues en general las personas tienden a ignorar los correos con una antigüedad superior a un par de días. En la llegada de un bus - si bien en ramos pasados se ha modelado con una exponencial, es decir, sin memoria - se asume que a medida que más se demora en llegar al paradero, cada vez la espera debe ser menor, pues tarde o temprano este deberá llegar.
Los otros análisis quedan propuestos, pero la intuición es fácil de comprender.

A partir de la tasa de riesgo, se puede definir unívocamente la distribución de una variable aleatoria no negativa a través de la siguiente integral:

$$F(t) = 1 - exp \left( -\int_{0}^{t} h(u)du \right)$$
Este concepto será útil para definir los modelos de duración en tiempo continuo en que la duración sí es un factor relevante

#### Modelo Weibull {-}

A pesar de las generalizaciones de las funciones de tasas de riesgo para generar modelos de tiempo de ocurrencia, nos enfocaremos en la distribución Weibull debido a que es fácil de trabajar y entrega una fórmula cerrada muy similar a la de la distribución exponencial. Se tiene que para la misma variable aleatoria T que se definió en la sección anterior, la probabilidad de ocurrencia de que un cliente pruebe nuestro producto en un tiempo inferior a t será:

$$F(t) = P(T \leq t) = 1 - e^{-\lambda t ^c}$$
Y la tasa de riesgo asociada a esta distribución:

$$h(t) = c \lambda t ^{c-1}$$
El primer parámetro $\lambda$ que compone la fórmula lo interpretamos como un parámetro de escala, mientras que el parámetro c le llamamos parámetro de forma. Es importante notar que para c = 1, la distribución se convierte en la distribución exponencial, por lo que se puede decir que la distribución Weibull es una generalización de la exponencial. Notar además que para c = 1, la tasa de riesgo es constante, lo que es consistente con la propiedad de pérdida de memoria de la
distribución exponencial.

**AQUÍ FIGURA 1.2**

En la distribución de Weibull generalizada por tanto, la propiedad de pérdida de memoria no aplica como en el caso de la exponencial, es decir, la probabilidad de ocurrencia varía a medida que pasa el tiempo:

$$P(T > s + t|T>s) = \frac{P(T> s+t)}{P(T> s)} = \frac{1-P(T \leq s+t)}{1-P(T \leq s)}= \frac{e^{-\lambda(s+t)^c}}{e^{-\lambda s^c}} $$

#### Modelo Gamma Weibull {-}

Una de las propiedades interesantes de la distribución Weibull, es que es sencillo introducir heterogeneidad sobre los parámetros, y de esa forma capturar los distintos posibles comportamientos de la población.

Al igual que en el modelo Gamma-Exponencial, asumiremos que el parámetro de escala λ está distribuido $\text{Gamma}(\alpha,r)$ en la población. La probabilidad de ocurrencia del consumo de los clientes se puede modelar por tanto de la siguiente forma:

\begin{array}{cc}
F(t) = P(T\leq t) &= \int_{0}^{\infty} \frac{(1 - e^{-\lambda t^c}) \alpha ^r \lambda ^{r-1}e^{-\alpha \lambda}}{\Gamma(r)} d \lambda\\
&= 1 - (\frac{\alpha}{\alpha + t^c})^r
\end{array}


 

## Modelos de Conteo

Permiten modelar cuantas veces los consumidores incurrirán en un comportamiento determinado en un período de tiempo (ejemplo: problema exposición publicitaria).

Algunas medidas de efectividad son:

- **Alcance:** Proporción de la población expuesta al evento al menos una vez durante el período: $1 − P(X_t = 0)$

- **Frecuencia promedio:** número promedio de exposiciones en el período entre aquellos que han experimentado el evento (por ejemplo, ver la valla publicitaria). $$\frac{\mathbb{E}(X_t)}{1-P(X_t =0)}$$


- **Puntos de rating brutos (GRPs):** número promedio de exposiciones por cada 100 personas.

$$100 \cdot \mathbb{E}(X_t)$$

\begin{equation} 
  P(N_t=m|\lambda) = \frac{(\lambda  t)^m e^{-\lambda t}}{m!}
  (\#eq:poisson)
\end{equation} 

lo cual corresponde a la probabilidad de que el número de exposiciones sea m en un intervalo de largo t.

Al igual que en los modelos anteriores, es posible incluir heterogeneidad asumiendo que el parámetro $\lambda$ distribuye de acuerdo a una determinada distribución. Suponiendo que dicha distribución es *Gamma*.




## Modelos de Elección


## Esperanzas Condicionales

## Variables explicativas

## Modelos Integrados

## Customer Lifetime Value: Caso Contractual




