# Modelos Probabilísticos

## Introducción
En este capítulo se abarcarán problemas con un enfoque probabilístico, esto es, que se asume que los tomadores de decisiones se comportan de manera aleatoria. Esto permite abordar una gran cantidad de problemas asociados al Marketing, los cuales se pueden caracterizar en tres tipos de modelos básicos: 

- *Duración*: La pregunta clave es ¿Cuándo?  Son situaciones ligadas a la duración de una determinada conducta del cliente, como por ejemplo: tiempo de permanencia en una compañía, tiempo de adopción de un cierto producto innovador, entre otros. Puede ser con tiempo continuo, o discreto.

- *Conteo*: La pregunta clave es ¿Cuántos?  Son situaciones ligadas al estudio de llegadas de clientes y contabilización de una determinada conducta, como por ejemplo: número de visitas a un portal web y la cantidad de productos comprados en una tienda de retail.

- *Elección*: La pregunta clave es ¿Cuál? Son situaciones asociadas a las decisiones de elección de un determinado cliente, como por ejemplo: clientes que eligen responder (o no) a una campaña publicitaria y la elección de cambiar (o no) de canal de televisión.

Cada uno se estos modelos tiene muchas aplicaciones dentro de diversas situaciones en la vida real. Comportamientos más complejos pueden ser descritos usando combinaciones de los modelos básicos. No obstante, nos centraremos en la resolución de problemas utilizando alguno de estos tres.  

## Metodología

Dicho enfoque posee una metodología de modelamiento sugerida, que comparten los modelos vistos a lo largo del curso.

La metodología consiste en:

1. Determinar el problema de decisión a estudiar y la información requerida.

2. Identificar el comportamiento observable de interés a nivel individual. Típicamente, se denota con una $x$.

3. Seleccionar la distribución de probabilidad que caracterice el comportamiento individual. Se consideran los parámetros de esta distribución, como características latentes a nivel individual. Típicamente, se denota con $f(x|\theta)$. 

4. Escoger la distribución que caracterice cómo las características latentes están distribuidas en la población. Se le llama distribución mixta o heterogénea. Típicamente, se denota con $g(\theta)$

5. Derivar la distribución agregada, o distribución observable, del comportamiento de interés. 

\begin{array}{cc}

f(x) = \int f(x|\theta) g(\theta) d\theta & \text{, para el caso continuo.}\\
 p(x) = \sum_{i} f(x|\theta)Pr(\theta = \theta_{i}) & \text{ 
 , para el caso discreto.}

\end{array}

6. Estimar los parámetros del modelo (de la distribución mixta), mediante el ajuste de la distribución agregada a los datos observados.

7. Usar los resultados para tomar una decisión sobre el problema de marketing en cuestión.


## Problemas 

### Problema 1 {-}

Hippi es una empresa nacional dedicada a la fabricación de productos para alta montaña. La
empresa cuenta con una base de datos que registra la compras que sus clientes en cada temporada
y busca estudiar el numero de parkas que los clientes compraran en la temporada. Para esto, se ha
formulado un modelo probabilístico donde el comportamiento de los clientes se describe como:

- Cada cliente compra un numero de parkas X que sigue una distribución geométrica. Esto es,condicional en el parámetro p de cada cliente, la función de probabilidad esta dada por:

$$Pr(X = x|p) = p(1-p)^x$$
- Los clientes son heterogéneos en su parámetro p el que esta distribuido en la población de acuerdo a una distribución Beta:

$$g(p|\alpha,\beta) = \frac{1}{B(\alpha,\beta)} p^{\alpha - 1}(1-p)^{\beta-1}$$

Se puede mostrar que la distribución de el número de compras para un cliente en la población, y su respectiva esperanza están dadas por:

$$Pr(X=x) = \frac{B(\alpha + 1, \beta + x)}{B(\alpha,\beta)} \qquad \mathbb{E}(X) = \frac{\alpha}{\beta - 1}$$

Siguiendo la convención adoptada en el curso, llamamos a este modelo Beta-Geométrico. 

1.  Muestre que la penetración de mercado (fracción de clientes que compró al menos una unidad) puede expresarse como $\frac{\beta}{\alpha+\beta}$.

2. Usando el método de los momentos, estime los parámetros del modelo. Para ello considere que la penetración de mercado es del 60 \% y que el numero promedio de parkas que compra un cliente (incluyendo aquellos que no compraron) es igual a 2.5.

3. Se desea extender el modelo para que además incluya un segmento de clientes que nunca compra. Para este segmento de clientes, $Pr(X = 0) = 1$. Sea $\pi$ la proporción de estos clientes en la población, y $(1-\pi)$ el segmento de clientes que se comporta de acuerdo al modelo Beta-Geométrico descrito anteriormente. Suponga que conoce $x_i$, el numero de compras hechas por cada cliente i en la base de datos (i = 1, ..., n). Deduzca la función de verosimilitud que utilizaría para estimar el modelo.


## Soluciones

### Problema 1 {-}

1. Muestre que la penetración de mercado (fracción de clientes que compró al menos una unidad) puede expresarse como $\frac{\beta}{\alpha+\beta}$.

Respuesta:

La penetración p viene dada por: 

\begin{align*}
        p_0 &= 1 - Pr(X = 0) \\
            &= 1 -  \frac{B(\alpha + 1, \beta)}{\alpha,\beta}\\
            &= 1 - \frac{\Gamma(\alpha +1)\Gamma(\beta)}{(\alpha+ 1 +\beta)} \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}\\
            &= 1 - \frac{\alpha\Gamma(\alpha) \Gamma(\beta)}{\alpha+\beta) \Gamma(\alpha+\beta)}\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha) \Gamma(\beta)}\\
            &= 1 - \frac{\alpha}{\alpha + \beta} = \frac{\beta}{\alpha + \beta}
\end{align*}


2. Usando el método de los momentos, estime los parámetros del modelo. Para ello considere que la penetración de mercado es del 60 \% y que el numero promedio de parkas que compra un cliente (incluyendo aquellos que no compraron) es igual a 2.5.

Respuesta:

Resolvemos el siguiente sistema: 

\begin{eqnarray}
        0,6 &= \frac{\beta}{\alpha + \beta} \\
        2,5 &= \frac{\alpha}{\beta-1}
\end{eqnarray}

Resolviendo el sistema:

$$\hat{\alpha} = \frac{10}{11} \qquad \hat{\beta} = \frac{15}{11}$$

3. Se desea extender el modelo para que además incluya un segmento de clientes que nunca compra. Para este segmento de clientes, $Pr(X = 0) = 1$. Sea $\pi$ la proporción de estos clientes en la población, y $(1 - \pi)$ el segmento de clientes que se comporta de acuerdo al modelo Beta-Geométrico descrito anteriormente. Suponga que conoce $x_i$, el numero de compras hechas por cada cliente i en la base de datos (i = 1, ..., n). Deduzca la función de verosimilitud que utilizaría para estimar el modelo.

Sea $n_x$ el número de clientes que compra x parkas. Entonces, la verosimilitud puede escribirse como:

$$L(\alpha,\beta,\pi |x) = \prod_{x=1}^{\infty} Pr = (X=x|\alpha,\beta,\pi)^{n_x}$$

donde,
\begin{array}{cc}
Pr(X=x|\alpha,\beta,\pi) & = \pi Pr(X=x|\text{ no adopta}) + (1 - \pi) Pr (X = x |\text{ puede adoptar})\\
  & =   \begin{cases}
  \pi + (1-\pi) \frac{B(\alpha+1,\beta)}{B(\alpha,\beta)} & x=0 \\
  (1-\pi)\frac{B(\alpha+1,\beta+x)}{B(\alpha,\beta)} & x>0
  \end{cases}
\end{array}
