FROM rocker/verse:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      texlive-latex-recommended \
      texlive-latex-extra \
      texlive-fonts-recommended \
      texlive-science \
      texlive-lang-spanish \
      texlive-xetex && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
